### PR TITLE
Add support for conan

### PR DESCRIPTION
**Pull request by baothientran**
This PR is used to accommodate the [conan support PR](https://github.com/CesiumGS/cesium-native/pull/261) for cesium-native
- Instead of hardcode the absolute library name, I just check if the file paths in the third-party directory contains the library name. If it does, then we will use that lib path for unreal plugin. That is because in Conan, the name of the library is inconsistent. For example, `tinyxml2` library can have the same name `tinyxml2.lib` for both debug and release build. However, `spdlog` can have `spdlogd.lib` for debug and `spdlog.lib` for release.
- Remove the third-party directory whenever we do cmake install cesium-native. That prevents the above solution mixes debug and release build together
- Add fmt lib to unreal since conan spdlog depends on it

TODO:
- [ ] Fixes CI build to install conan

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @baothientran!

* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @baothientran! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @baothientran! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @baothientran! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @baothientran! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @baothientran! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @baothientran! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @baothientran! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by csciguy8** [comment]
Closing this draft PR due to its age. (over 1 year of inactivity).

From discussions with @kring, integrating conan was fairly difficult due to timing between conan versions and due to the framework itself. Ultimately, robust dependency management is still needed for both this repo and cesium-native, whether we use the latest conan version, VCPKG, or some other solution.

**Pull request closed without merging**
