### PR TITLE
Update FeatureId::propertyTable usage to fit with cesium-native changes

### PR DESCRIPTION
**Pull request by azrogers**
`FeatureId::propertyTable` is now no longer an std::optional, which requires a few small changes.

### CODE REVIEW

**Comment by j9liu** [comment]
Unfortunately it seems like iOS isn't happy with the recent cesium-native changes :/ 

It seems like these are the culprits:

```
/Users/runner/work/cesium-unreal/cesium-unreal/extern/cesium-native/CesiumUtility/src/Uri.cpp:270:38: error: 'path' is unavailable: introduced in iOS 13.0
  if constexpr (std::filesystem::path::preferred_separator == '\\') {
                                     ^
In file included from /Users/runner/work/cesium-unreal/cesium-unreal/extern/cesium-native/CesiumUtility/src/Uri.cpp:9:
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
/Users/runner/work/cesium-unreal/cesium-unreal/extern/cesium-native/CesiumUtility/src/Uri.cpp:322:38: error: 'path' is unavailable: introduced in iOS 13.0
  if constexpr (std::filesystem::path::preferred_separator == '\\') {
                                     ^
In file included from /Users/runner/work/cesium-unreal/cesium-unreal/extern/cesium-native/CesiumUtility/src/Uri.cpp:9:
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
2 errors generated.
```

**Comment by kring** [comment]
I fixed the above by updating cesium-native to inclue CesiumGS/cesium-native#891, so merge that first.

**Comment by kring** [comment]
This PR now updates cesium-native to include CesiumGS/cesium-native#892 too.

**Comment by csciguy8** [comment]
This looks ready to go. I'll merge unless there are objections...

**Pull request merged**
