### PR TITLE
Fix movie rendering problems with Google Maps Photorealistic 3D Tiles by updating cesium-native

### PR DESCRIPTION
**Pull request by kring**
Depends on CesiumGS/cesium-native#686.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @kring!

* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by kring** [comment]
I'm going to merge this because it only updates cesium-native to the latest main.

**Comment by j9liu** [comment]
We forgot to add this to CHANGES.md!

**Comment by j9liu** [comment]
Just pushed a commit to main to add the missing changelog entry, feel free to reword as needed.

**Pull request merged**
