### PR TITLE
WebP support

### PR DESCRIPTION
**Pull request by joseph-kaile**
Native side here: https://github.com/CesiumGS/cesium-native/pull/542

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @joseph-kaile!

* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
    * Maintainers, [here's how to check](https://github.com/CesiumGS/cesium/blob/master/Documentation/Contributors/CLAs/README.md) for a submitted CLA.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by nithinp7** [comment]
Thanks @joseph-kaile! Cross posting my comment from the native PR regarding the few changes I added:
>Thanks @joseph-kaile, this looks great! I tested it with the Sponza model tiled on Cesium Ion with the WebP option enabled. It didn't work and I realized Ion outputs webp images wrapped in the EXT_texture_webp. So I generated that extension here and made some small adjustments on the Unreal side to use the texture source found in the extension, if it exists. Webp images should work both ways now, within the extension or just within the regular glTF texture, just like KTX.

**Comment by noySimplex** [comment]
Will webp support be merged into ue5-main branch?

with the latest version in UE5 I still get the error:
> Failed resolving external glTF buffers from ...(URL).b3dm:
> - Image not of any known type, or corrupt
> - Declared image MIME Type: image/webp

**Comment by kring** [comment]
@noySimplex Both UE4 and UE5 have had WebP support for awhile now, so we're not sure why you might be seeing that error. Can you share a tileset with us to demonstrate the problem?

**Pull request merged**
