### PR TITLE
Added missing multiple frustums to CHANGES.md + small fixes

### PR DESCRIPTION
**Pull request by nithinp7**

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @nithinp7!

* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by nithinp7** [comment]
@kring I just saw [this forum post](https://community.cesium.com/t/crash-on-play-or-packaged-project/14716). Do you think the last commit here might fix the reported crash?

**Comment by kring** [comment]
Good question! I posted to the forum asking the person to try the build from this branch.

**Comment by kring** [comment]
Thanks @nithinp7!

**Pull request merged**
