### PR TITLE
UE5 build warning fixes

### LINKED ISSUE #1314: Deprecation warnings when building Cesium for Unreal
I'm seeing a couple deprecation warnings when building Cesium for Unreal

> 1>C:\...\Plugins\cesium-unreal\Source\CesiumEditor\Private\CesiumIonTokenTroubleshooting.cpp(326): warning C4996: 'FEditorStyle::GetBrush': FEditorStyle::GetBrush() is deprecated, use FAppStyle::GetBrush() instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.

> 1>C:\...\Plugins\cesium-unreal\Source\CesiumRuntime\Private\CesiumTextureUtility.cpp(362): warning C4996: 'RHICreateTexture2D': FRHITexture2D is deprecated, please use RHICreateTexture(const FRHITextureCreateDesc&). Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.

### PR DESCRIPTION
**Pull request by TeraDanielR**
Fixes #1314
Fixes several UE5.3 build warnings when packaging.

### CODE REVIEW

**Comment by kring** [comment]
Looks like there might be some problems on some platforms/versions. Perhaps just a missing `#include`. Mind taking a look?
https://github.com/CesiumGS/cesium-unreal/actions/runs/7282601826

**Comment by j9liu** [comment]
@TeraDanielR It looks like CI is complaining about the use of `#if` instead of `#ifdef`. Do you mind changing these for the lines you added?

**Comment by TeraDanielR** [comment]
I will do that now! Thanks for the info!

**Comment by kring** [comment]
Sorry I don't think switching to `ifdef` is the right solution here (despite the error message suggesting that it is). You should be able to fix it by adding `#include "CesiumCommon.h"` to the source files that use these `ENGINE_VERSION` macros, because that's the header where they're defined. Once that's included, `ENGINE_VERSION_5_3_OR_HIGHER` are _defined_ in all versions of UE, but they're defined to either true or false depending on the UE version. Using `ifdef` doesn't work, because `#ifdef ENGINE_VERSION_5_3_OR_HIGHER` will be considered true even on UE 5.2 where the value is false (because it's still defined!) when the header is included. And meanwhile `#ifdef ENGINE_VERSION_5_3_OR_HIGHER` will evaluate to false even on UE 5.3 when the header is not included (because it's not defined). Not sure if all that makes sense, but the short version is: switch back to `#if` and include the `CesiumCommon.h` header in any .cpp files that use these version macros.

**Comment by TeraDanielR** [comment]
Thanks for the info Kevin! I have pushed the changes you suggested.

**Comment by azrogers** [comment]
@TeraDanielR Everything looks good here to me. Can you just push an edit to CHANGES.md adding a bullet point under Fixes for your change? Something like "Fixed deprecation warning messages when packaging in Unreal 5.3." Once that's in I can get this merged!

**Comment by FaradaysInfinity** [comment]
I am just searching around for possible solutions and am unsure if the commits in this thread will apply, but i am getting  Build Failed in 5.3.2 and getting these errors stated

In planetrack.cpp:
...\Unreal Projects\Global_Interactive_1\Source\Global_Interactive_1\PlaneTrack.cpp(48): error C2039: 'TransformLongitudeLatitudeHeightToUnreal': is not a member of 'ACesiumGeoreference'

...\Unreal Projects\Global_Interactive_1\Plugins\Marketplace\CesiumForUnreal\Source\CesiumRuntime\Public\CesiumGeoreference.h(35): note: see declaration of 'ACesiumGeoreference'

...\Unreal Projects\Global_Interactive_1\Source\Global_Interactive_1\PlaneTrack.cpp(58): warning C4996: 'ACesiumGeoreference::GetGeoTransforms': Use transformation functions on ACesiumGeoreference and UCesiumWgs84Ellipsoid instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.


I am fairly new to c++ as well, so i am stumbling through all this as I go. I would appreciate any help

**Comment by csciguy8** [comment]
Hi @FaradaysInfinity, I don't believe this PR is related to your problems. This is addressing deprecation warnings, not build errors.

Would you mind moving your question over to our Cesium for Unreal forum?
https://community.cesium.com/c/cesium-for-unreal/10

Thanks!

**Pull request merged**
