### PR TITLE
Add support for small tool bar icons

### PR DESCRIPTION
**Pull request by javagl**
Fixes https://github.com/CesiumGS/cesium-unreal/issues/485

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @javagl!

* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by javagl** [comment]
CesiumUnreal icons!!!

CesiumUnreal icons but small!!!

**Comment by shehzan10** [comment]
@javagl Is this changing the default icon size, or it is only if a user has edited the setting in their editor that we are adding support for?

**Comment by javagl** [comment]
It does not change the default icon size. The first screenshot shows the appearance with the default setting (i.e. with the global "Use Small Tool Bar Icons" being *disabled*), and this has not changed. The second screenshot shows the appearance after the setting was *enabled*. Then, it shows the smaller icons. (Before this change, enabling this setting just caused all Cesium icons to disappear).

**Comment by kring** [comment]
👍

**Pull request merged**
