### PR TITLE
Fix `FName` memory issue when running for extended periods of time

### LINKED ISSUE #1422: FName Overflow,  allocated 1024MB of string data. FName strings are never freed and should be created sparingly. Some system might be generating too many FNames, see call stack.
When I run my application for several hours (at least 5 hours) I get the error:

```
[2024.05.10-16.21.29:800][693]LogStreaming: Display: 0.160 ms for processing 89658 objects in RemoveUnreachableObjects(Queued=0, Async=0). Removed 0 (537->537) packages and 0 (1573->1573) public exports.
Assertion failed: CurrentBlock < FNameMaxBlocks [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\UObject\UnrealNames.cpp] [Line: 698] 
FName overflow, allocated 1024MB of string data. FName strings are never freed and should be created sparingly. Some system might be generating too many FNames, see call stack. 
```

The stack trace of this comes from Cesium:

```
 	INEOS-Win64-DebugGame.exe!FNameEntryAllocator::AllocateNewBlock(void)	C++
 	INEOS-Win64-DebugGame.exe!FNamePoolShard<1>::CreateAndInsertEntry<class FWriteScopeLock>(struct FNameSlot &,struct FNameValue<1> const &)	C++
 	INEOS-Win64-DebugGame.exe!FNamePool::Store(struct FNameStringView)	C++
 	INEOS-Win64-DebugGame.exe!FNameHelper::FindOrStoreString(struct FNameStringView,enum EFindName)	C++
 	INEOS-Win64-DebugGame.exe!FNameHelper::MakeWithNumber(struct FWideStringViewWithWidth,enum EFindName,int)	C++
 	INEOS-Win64-DebugGame.exe!FName::FName(wchar_t const *,enum EFindName)	C++
 	INEOS-Win64-DebugGame.exe!FStatNameAndInfo::ToLongName(class FName,char const *,char const *,wchar_t const *,bool)	C++
 	INEOS-Win64-DebugGame.exe!FStatMessage::FStatMessage(class FName,enum EStatDataType::Type,char const *,char const *,wchar_t const *,bool,bool,bool,enum FWindowsPlatformMemory::EMemoryCounterRegion)	C++
 	INEOS-Win64-DebugGame.exe!FStartupMessages::AddMetadata(class FName,wchar_t const *,char const *,char const *,wchar_t const *,bool,enum EStatDataType::Type,bool,bool,enum FWindowsPlatformMemory::EMemoryCounterRegion)	C++
 	INEOS-Win64-DebugGame.exe!FUObjectItem::CreateStatID(void)	C++
 	INEOS-Win64-DebugGame.exe!FPrimitiveSceneProxy::FPrimitiveSceneProxy(class UPrimitiveComponent const *,class FName)	C++
 	INEOS-Win64-DebugGame.exe!FStaticMeshSceneProxy::FStaticMeshSceneProxy(class UStaticMeshComponent *,bool)	C++
 	INEOS-Win64-DebugGame.exe!UStaticMeshComponent::CreateSceneProxy(void)	C++
 	INEOS-Win64-DebugGame.exe!FScene::AddPrimitive(class UPrimitiveComponent *)	C++
 	INEOS-Win64-DebugGame.exe!UPrimitiveComponent::CreateRenderState_Concurrent(class FRegisterComponentContext *)	C++
 	INEOS-Win64-DebugGame.exe!UStaticMeshComponent::CreateRenderState_Concurrent(class FRegisterComponentContext *)	C++
 	INEOS-Win64-DebugGame.exe!UActorComponent::ExecuteRegisterEvents(class FRegisterComponentContext *)	C++
 	INEOS-Win64-DebugGame.exe!UActorComponent::RegisterComponentWithWorld(class UWorld *,class FRegisterComponentContext *)	C++
 	INEOS-Win64-DebugGame.exe!loadPrimitiveGameThreadPart(CesiumGltf::Model & model, UCesiumGltfComponent * pGltf, LoadGltfResult::LoadPrimitiveResult & loadResult, const glm::mat<4,4,double,0> & cesiumToUnrealTransform, const Cesium3DTilesSelection::Tile & tile, bool createNavCollision, ACesium3DTileset * pTilesetActor) Line 3235	C++
>	INEOS-Win64-DebugGame.exe!UCesiumGltfComponent::CreateOnGameThread(CesiumGltf::Model & model, ACesium3DTileset * pTilesetActor, TUniquePtr<UCesiumGltfComponent::HalfConstructed,TDefaultDelete<UCesiumGltfComponent::HalfConstructed>> pHalfConstructed, const glm::mat<4,4,double,0> & cesiumToUnrealTransform, UMaterialInterface * pBaseMaterial, UMaterialInterface * pBaseTranslucentMaterial, UMaterialInterface * pBaseWaterMaterial, FCustomDepthParameters CustomDepthParameters, const Cesium3DTilesSelection::Tile & tile, bool createNavCollision) Line 3308	C++
 	INEOS-Win64-DebugGame.exe!UnrealResourcePreparer::prepareInMainThread(Cesium3DTilesSelection::Tile & tile, void * pLoadThreadResult) Line 730	C++
 	[External Code]	
 	INEOS-Win64-DebugGame.exe!ACesium3DTileset::Tick(float DeltaTime) Line 2059	C++
 	[External Code]	
```

There are a few cesium error logs just before this happens:

```
[2024.05.10-16.20.28:696][230]LogStreaming: Display: 0.407 ms for processing 181158 objects in RemoveUnreachableObjects(Queued=0, Async=0). Removed 0 (537->537) packages and 0 (1573->1573) public exports.
The thread 1568 has exited with code 0 (0x0).
The thread 15080 has exited with code 0 (0x0).
The thread 8276 has exited with code 0 (0x0).
The thread 23964 has exited with code 0 (0x0).
[2024.05.10-16.20.45:346][693]LogCesium: Error: [2024-05-10 17:20:45.347] [error] [TilesetJsonLoader.cpp:889] Received status code 401 for tile content https://assets.ion.cesium.com/us-east-1/asset_depot/96188/OpenStreetMap/CWT/2024-03-04/14/16583/4425.b3dm?v=17

[2024.05.10-16.20.45:358][694]LogCesium: Error: [2024-05-10 17:20:45.359] [error] [TilesetJsonLoader.cpp:889] Received status code 401 for tile content https://assets.ion.cesium.com/us-east-1/asset_depot/96188/OpenStreetMap/CWT/2024-03-04/14/16582/4425.b3dm?v=17

[2024.05.10-16.20.45:369][695]LogCesium: Error: [2024-05-10 17:20:45.370] [error] [TilesetJsonLoader.cpp:889] Received status code 401 for tile content https://assets.ion.cesium.com/us-east-1/asset_depot/96188/OpenStreetMap/CWT/2024-03-04/14/16583/4424.b3dm?v=17

The thread 13460 has exited with code 0 (0x0).
[2024.05.10-16.20.45:403][698]LogCesium: Error: [2024-05-10 17:20:45.404] [error] [TilesetJsonLoader.cpp:889] Received status code 401 for tile content https://assets.ion.cesium.com/us-east-1/asset_depot/96188/OpenStreetMap/CWT/2024-03-04/14/16582/4424.b3dm?v=17

The thread 24220 has exited with code 0 (0x0).
The thread 13784 has exited with code 0 (0x0).
The thread 24268 has exited with code 0 (0x0).
The thread 24036 has exited with code 0 (0x0).
The thread 1440 has exited with code 0 (0x0).
[2024.05.10-16.21.29:800][693]LogStreaming: Display: 0.160 ms for processing 89658 objects in RemoveUnreachableObjects(Queued=0, Async=0). Removed 0 (537->537) packages and 0 (1573->1573) public exports.
Assertion failed: CurrentBlock < FNameMaxBlocks [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Core\Private\UObject\UnrealNames.cpp] [Line: 698] 
FName overflow, allocated 1024MB of string data. FName strings are never freed and should be created sparingly. Some system might be generating too many FNames, see call stack. 
[2024.05.10-16.21.39:374][553]LogOutputDevice: Warning: 
```

For reference, I am using unreal engine 5.2 and Cesium v2.0.0 install visa the epic game store

### PR DESCRIPTION
**Pull request by csciguy8**
Closes #1422.

A user reported an error with `FName` allocations when running for long periods of time (5 hours).

Interesting output from Unreal
`FName overflow, allocated 1024MB of string data. FName strings are never freed and should be created sparingly`

In `loadPrimitiveGameThreadPart` we create a new `FName` object for every primitive loaded. In some cases, these can be fairly large (Ex. 165 characters) as they are essentially the url to the asset that was fetched.

This PR solves the problem by avoiding creating an `FName` entirely. 

Ran through all the samples level and didn't see any issues. Also, these meshes and components are not visible in the Outliner window, so there's no apparent user facing change either.

### CODE REVIEW

**Comment by csciguy8** [comment]
> so there's no apparent user facing change either.

One use for named components is for debugging, specifically when wanting to know what assets are mapped to what you are actually looking at. (thanks @kring for mentioning)

Here's how... click on a  piece of the terrain in the viewport, try to delete it. You'll see a console message like this...

`Cmd: DELETE
Cmd: ACTOR DELETE
LogEditorActor: Cannot delete component CesiumGltfPrimitiveComponent /Game/CesiumSamples/Maps/01/01_CesiumWorld.01_CesiumWorld:PersistentLevel.CesiumWorldTerrain.CesiumGltfComponent_282.https://assets.ion.cesium.com/us-east-1/asset_depot/1/CesiumWorldTerrain/v1.2/16/20975/46531.terrain?v=1.2.0&extensions=octvertexnormals-metadata-watermask mesh 0 primitive 0: Can't delete non-editable component.
`

Is this valuable enough to keep the FName creation around? Probably not. And if debugging in this way, you can just make a test branch, and put the naming back in anyway. Interesting though.

**Comment by azrogers** [comment]
I think this suggestion was made a bit jokingly, but I do think it would be good to wrap this in a define. Something like `CESIUM_CREATE_TILE_NAMES`. Would mean that future developers don't have to hunt through old pull requests to figure out how to enable this debugging feature.

**Comment by csciguy8** [comment]
@azrogers Sensible suggestion. I've made this change, and it's ready for another look.

**Comment by azrogers** [comment]
Looks good to me. Thanks @csciguy8!

**Pull request merged**
