### PR TITLE
Cartographic Polygon on Quick Add Basic Actors panel

### PR DESCRIPTION
**Pull request by argallegos**
This adds Cesium Cartographic Polygon to the Quick Add panel, under the Basic Actors section. Fixes https://github.com/CesiumGS/cesium-unreal/issues/716

image

This spawns the Cartographic Polygon at the world/georeference origin, which may be less useful than drag and dropping it to your desired location, but it's good to have the option. 

I had one question about the implementation that I wasn't sure about. I copied the code to add the actor from the code to add a blank 3D Tileset to the level, lines 318-328 of IonQuickAddPanel.cpp. The `AddActor()` function for the blank tileset included the `EObjectFlags` `RF_Public` and `RF_Transactional`. I wasn't able to find much documentation about what they do - looks like `RF_Transactional` allows users to undo the actor addition (or allows all actions involving the actor to be undone?), but I don't understand what `RF_Public` does. 

I included them in the new function (line 242, `IonQuickAddPanel::AddCartoPolygonToLevel()`) to be safe,  but please advise on whether they are needed or should be removed.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @argallegos!

* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium-unreal/blob/cartopolygon-in-quickadd-panel/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by kring** [comment]
Looks good @argallegos! Just two small things:
* Update CHANGES.md to mention this addition.
* Don't use abbreviations. "cartographic" not "carto".

**Comment by argallegos** [comment]
Thanks @kring, updated.

**Comment by kring** [comment]
Thanks @argallegos!

**Pull request merged**
