### PR TITLE
Reimport 1x1 textures as 4x4

### PR DESCRIPTION
**Pull request by joseph-kaile**
The tile sets are black in 5.3 iOS for some unknown reason. Resizing the 1x1 textures to 4x4 textures makes the issue go away.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @joseph-kaile!

* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
    * Maintainers, [here's how to check](https://github.com/CesiumGS/cesium/blob/master/Documentation/Contributors/CLAs/README.md) for a submitted CLA.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @joseph-kaile! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by csciguy8** [comment]
Fix seems to relate to
https://github.com/CesiumGS/cesium-unreal/issues/1391

... although nothing in the Unreal docs explicitly say that 1x1 textures are to be avoided...
https://docs.unrealengine.com/4.27/en-US/RenderingAndGraphics/Textures/SupportAndSettings/

image

**Comment by azrogers** [comment]
Reverted my code changes, it's a lot easier to just get this in with just the asset changes than to rename the assets, rename their usage in the code, make sure other assets still point to it correctly, etc... and I don't think the name transparent1x1 is really going to cause that much confusion.

**Pull request merged**
