### PR TITLE
remove the baseColorFactor alpha check when selecting base material

### PR DESCRIPTION
**Pull request by EvenZHAnglll**
fix https://github.com/CesiumGS/cesium-unreal/issues/1160

### CODE REVIEW

**Comment by j9liu** [comment]
Thanks for the pull request @EvenZHAnglll!

Could you please sign our [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla)? Once it's signed, we'll be able to take a look at your changes. Thank you!

**Comment by EvenZHAnglll** [comment]
> Thanks for the pull request @EvenZHAnglll!
> 
> Could you please sign our [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla)? Once it's signed, we'll be able to take a look at your changes. Thank you!

Sure. I've signed the CLA.

**Comment by j9liu** [comment]
Looks good to me @EvenZHAnglll ! Can you do one more thing: add a note about this to [CHANGES.md](https://github.com/CesiumGS/cesium-unreal/blob/main/CHANGES.md)?

You can copy paste this at the top, if you'd like: 

> ? - ?
> 
> Fixes 🔧
> - Removed unnecessary alpha check when selecting translucent base materials.

**Comment by EvenZHAnglll** [comment]
> Looks good to me @EvenZHAnglll ! Can you do one more thing: add a note about this to [CHANGES.md](https://github.com/CesiumGS/cesium-unreal/blob/main/CHANGES.md)?
> 
> You can copy paste this at the top, if you'd like:
> 
> > ? - ?
> > Fixes 🔧
> > 
> > * Removed unnecessary alpha check when selecting translucent base materials.

OK, it's added.

**Comment by j9liu** [comment]
Sorry for the wait on this @EvenZHAnglll ! Merging now, thank you for the contribution :pray:

**Pull request merged**
