### PR TITLE
Dynamic camera tweaks and fixes

### PR DESCRIPTION
**Pull request by xuelongmu**
Some simple tweaks and improvements to dynamic camera feel.

- Added FlyTo curves
- Increased max speed cap on manual mode

Todo: profile floating pawn vs dynamic pawn performance
Ref: #11

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @xuelongmu!

* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by xuelongmu** [comment]
@nithinp7 I tried to address [some of your comments](https://github.com/CesiumGS/cesium-unreal/pull/319#issuecomment-828165805) from #319, specifically:
- Manual mode speed cap
- Float curves
- Fixed issue with speed multipliers not getting applied
- I did another pass at the movement logic and simplified it. From the previous PR I had already implemented a way for the camera not to slow down when passing over things (as long as camera is looking reasonably far away). If you still notice it, let me know.

@argallegos Feel free to test this out as well. I had modified some of the speed curves compared with the tutorial, based on what I saw when creating the click to run demo.

**Comment by kring** [comment]
This looks good to me. Any reason we can't merge it @nithinp7 or @argallegos?

**Comment by nithinp7** [comment]
Great work @xuelongmu I think this looks good on keyboard, I'm excited to try it out with a controller too when I get back to my apartment! Can you update the Changes.md? I can merge it then.

**Comment by xuelongmu** [comment]
Thanks @nithinp7 @kring , changes have been updated 👍

**Pull request merged**
