### PR TITLE
Add property texture styling

### PR DESCRIPTION
**Pull request by j9liu**
This continues off the work that was done in #1254, allowing property textures to be used in metadata styling. You can test this using the US Muscatatuck dataset I linked in the previous PR and compare the result with this [CesiumJS sandcastle](https://sandcastle.cesium.com/?src=Custom%20Shaders%20Property%20Textures.html&label=3D%20Tiles%20Next).

This is what it looks like if you map the horizontal uncertainty to the red channel, and the vertical uncertainty to the yellow.
image

I also added some HLSL safety measures that weren't previously in place, and replaced hardcoded node X / Y values with a more responsive system.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @j9liu!

* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by kring** [comment]
I'm having trouble getting this to work. It's pretty likely I just don't know what I'm doing. Here's what I did:

1. Downloaded the US Muscatatuck dataset from the Google Drive link in your other PR, and unzipped it somewhere on my system.
2. In Unreal, created a new level and added a CesiumSunSky and a Blank Tileset. Set the tileset URL to a `file:///` URL to the tileset.json on my system.
3. Double-clicked the tileset to zoom to it. It appeared:
image
4. Added a CesiumFeaturesMetadata component to the Cesium3DTileset and clicked Auto Fill. Some reasonable-looking stuff appeared:

image

6. Clicked Generate Tileset. The generated material layer looks pretty sparse:

image

I briefly stepped through the code to try to see what I missed, but `GenerateMaterialNodes` seems to not do much if there are no feature ID sets? I don't really know what I'm doing.

**Comment by kring** [comment]
I've deleted my comment above because I realized what I was doing wrong. I was just running the wrong branch. 😬 Sorry for the noise!

**Comment by kring** [comment]
This looks great, thanks @j9liu!

**Pull request merged**
