### PR TITLE
screenspacecontroller support for cesium unreal

### PR DESCRIPTION
**Pull request by jiangheng90**
fullfill the feature from [community](https://community.cesium.com/t/screenspacecontroller-for-cesiumunreal/32267/3)

### CODE REVIEW

**Review by jiangheng90 — COMMENTED** [review]
after  [CHANGES.md](https://github.com/CesiumGS/cesium-unreal/blob/main/CHANGES.md) update I will add the Additions

**Comment by jiangheng90** [comment]
the globe pawn is support the full feature when georeference origin placement in true origin,in cartographic some feature is disabled. Use the quick add panel. It will add in proper place.

**Comment by FEJackFly** [comment]
When is it online? It's urgent

**Comment by chenguang1994** [comment]
expect

**Comment by LuLuEarl** [comment]
The operation is smooth，Thank you for sharing

**Comment by FEJackFly** [comment]
image

What should I do when generating a solution and reporting error MSB307 is reported

ue 5.3
Visual Studio 2022 
cmake 3.30

**Comment by pjiang9** [comment]
Thank you for fulfilling the GlobePawn！
Yet there are situations that will make Unreal Engine Crash.
It is hard to describe how to reproduce the crash situations.
It is likely to crash when zoom in and zoom out several times,  and  the viewport will be complete black, then UE will shut down.
The following is the log captured when UE crashes. Much appreciated if you could look into it and fix it.

UE5.3,CesiumforUnreal2.5.0
UnrealEditor_CesiumRuntime!CesiumGeometry::Plane::Plane()
UnrealEditor_CesiumRuntime!Cesium3DTilesSelection::createCullingVolume()
UnrealEditor_CesiumRuntime!Cesium3DTilesSelection::ViewState::create()
UnrealEditor_CesiumRuntime!ACesium3DTileset::CreateViewStateFromViewParameters() [E:\UnrealPack\CesiumforUE\UE_5.3\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\Cesium3DTileset.cpp:1673]
UnrealEditor_CesiumRuntime!ACesium3DTileset::Tick() [E:\UnrealPack\CesiumforUE\UE_5.3\CesiumForUnreal\HostProject\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\Cesium3DTileset.cpp:2123]
UnrealEditor_Engine


UE5.3 CesiumforUnreal2.7.0
UnrealEditor_CesiumRuntime!Cesium3DTilesSelection::createCullingVolume()
UnrealEditor_CesiumRuntime!Cesium3DTilesSelection::ViewState::create()
UnrealEditor_CesiumRuntime!ACesium3DTileset::CreateViewStateFromViewParameters() [E:\UE53Projects\GlobePawn\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\Cesium3DTileset.cpp:1630]
UnrealEditor_CesiumRuntime!ACesium3DTileset::Tick() [E:\UE53Projects\GlobePawn\Plugins\CesiumForUnreal\Source\CesiumRuntime\Private\Cesium3DTileset.cpp:2082]

**Comment by andiven** [comment]
@jiangheng90  I hope Touch support can be added.

**Comment by kring** [comment]
Hi @jiangheng90, sorry to see you close this. We've been slow to review it, but it's definitely a valuable contribution!

**Comment by zzzsssddd999** [comment]
GlobePawn有BUG，用这个后，操作时UE编辑器运行窗口会突然黑屏，然后UE编辑器会崩溃（在编辑器运行后操作最多20分钟必出，该BUG概率挺高，最快可能1分钟就崩溃），UE5.3，在cesium unreal2.5，2.7版本都存在。换回cesium unreal自带的DynamicPawn再怎么操作都不会黑屏崩溃。

**Comment by jiangheng90** [comment]
@kring I'm sorry for the pull request close.

It's been more than half a year since the end of development of this feature, and many of the technical details in it are not so familiar to me now. 

Secondly, because of the development of this feature, some people found my social accounts under the social media and caused some trouble to my privacy, which I didn't want.

Right now, can u just make a feature branch and I make my pull request to this branch. it will take a long time to make this feature be all right and I think this is a better way for both of us to push it forward.

**Comment by kring** [comment]
> It's been more than half a year since the end of development of this feature, and many of the technical details in it are not so familiar to me now.

Understood. It's only been a couple of months since you opened the PR, but even that is too long.

> Secondly, because of the development of this feature, some people found my social accounts and caused some trouble to my privacy, which I didn't want.

Oh no, really sorry that's happening to you. That sort of behavior definitely has no place in the Cesium community. Let us know if we can help in any way.

> Right now, can u just make a feature branch and I make my pull request to this branch. it will take a long time to make this feature be all right and I think this is a better way for both of us to push it forward.

Ok, I created a branch called `screen-space-controller` in this repo. It's just a copy of main.

**Comment by jiangheng90** [comment]
@kring I have all ready make a new pull request.

**Comment by lky5230** [comment]
> GlobePawn有BUG，用这个后，操作时UE编辑器运行窗口会突然黑屏，然后UE编辑器会崩溃（在编辑器运行后操作最多20分钟必出，该BUG概率挺高，最快可能1分钟就崩溃），UE5.3，在cesium unreal2.5，2.7版本都存在。换回cesium unreal自带的DynamicPawn再怎么操作都不会黑屏崩溃。

哥，最新的Cesium For Unreal插件怎么使用这个Pawn呀

**Comment by pjiang9** [comment]
> > GlobePawn有BUG，用这个后，操作时UE编辑器运行窗口会突然黑屏，然后UE编辑器会崩溃（在编辑器运行后操作最多20分钟必出，该BUG概率挺高，最快可能1分钟就崩溃），UE5.3，在cesium unreal2.5，2.7版本都存在。换回cesium unreal自带的DynamicPawn再怎么操作都不会黑屏崩溃。
> 
> 哥，最新的Cesium For Unreal插件怎么使用这个Pawn呀

要修复这个Bug,请查看【Cesium for Unreal 解决GlobePawn致使UE崩溃的方法-哔哩哔哩】 https://b23.tv/OUdesOC

**Pull request closed without merging**
