### PR TITLE
Fix broken euler angles and quaternion conversions

### PR DESCRIPTION
**Pull request by nithinp7**
Somewhat related to #265 and #733.

I think our East-North-Up <--> Unreal conversion functions in the Georeferencing API are quite broken. This PR attempts to fix some if not all of it. 

We had functions to transform rotators (pitch, yaw, roll) from ENU to Unreal and vice-versa. These were implemented by:
Step 1: Convert FRotators (pitch, yaw, roll) into quaternions.
Step 2: Compute the Unreal <--> ENU matrix and convert the rotation part into a quaternion.
Step 3: And then multiply the above two quaternions to transform a rotation between Unreal and ENU.
Step 4: And of course convert back from quaternion to pitch, yaw, roll at the end in the destination coordinate system.

Implementation mistakes fixed:
- There was a glaring mistake (made by me!) that flipped the direction of conversions between UE and ENU. So UE to ENU mistakenly converted from ENU to UE and vice-versa. In fact I had started fixing it here #733 but found that rotations still remained broken overall.
- It turns out ComputeEastNorthUpToUnreal was _actually_ computing a East-South-Up to Unreal pure rotation matrix! In fact some code calling this function from the GlobeAwareDefaultPawn and the GlobeAnchorComponent seemed to acknowledge in comments that the result was an ESU to Unreal rotation. 
- The rotator and quaternion conversion functions were built upon the above function and so were mistakenly doing ESU to UE and vice versa. In fact, an _actual_ ENU --> Unreal matrix converted to a quaternion (step 2) might be undefined (or at least incorrect to use) since ENU and Unreal have opposite handedness.
- Some code to convert back from glm quaternions to Unreal FRotators was innocently using the pitch(..), yaw(..), and roll(..) functions from the glm library. While glm is usually agnostic of coordinate system conventions (e.g., handedness, up-direction, etc.), computing pitch, yaw, and roll from a quaternion implies some assumed convention of which axis is up, right, and forward and an implied rotation-order convention for euler angles (or yaw, pitch, roll in this case). Even determining whether positive angles rotate CW or CCW for each axis comes down to convention. So it's no surprise that the assumed conventions of glm's quaternion --> pitch, yaw, roll did not match that of Unreal. 

My solution was primarily to get rid of ENU <--> UE conversions and just do ESU <--> UE instead. This will make it much easier to reason about the rotations since the rotation conventions and handedness will remain the same through the conversion.

TODOs before merge:
* [x] Address and remove TODOs in the code
* [x] Add backward compatibility via core-redirects where possible. Some of these functions were completely broken, so we'll have to weigh how likely it is somebody is relying on the broken version.
* [ ] Find a way to unit test this, even if it is ad-hoc! Or alternatively move this into Cesium Native and unit test there??

I started looking into this after seeing this community forum post recently:
https://community.cesium.com/t/correct-way-to-set-euler-angles-for-actor-in-c/20808

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @nithinp7!

* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by kring** [comment]
Thanks @nithinp7, your changes all make sense to me!

This is a huge improvement that fixes the biggest problems, but I think we would still benefit from a more holistic look at how this all works. For example, the notion of converting "ESU" to Unreal is... weird. The Unreal coordinate system in this case _is_ an ESU system, right? So what are we actually doing? Well, we're transforming between an ESU system centered at globe position and an ESU system centered at another globe position. And if I'm not mistaken, both use units of centimeters (which is not 100% clear in the API).

If we switch Unreal to use the new `LocalHorizontalCoordinateSystem` in cesium-native, one way we could make this more obvious and explicit is by allowing transformations between two `LocalHorizontalCoordinateSystem` instances. So we can have one instance that represents the georeferenced Unreal world coordinate system. And another that represents an ESU system (or whatever we want) somewhere on the globe, and then we can ask for a matrix to transform between them. And then maybe we don't need all these difficult-to-name-precisely conversion methods. (they're difficult for us to name, but it's probably even more difficult for our users to decide which one to use!)

Mostly thinking out loud here, we certainly don't need to implement anything like this for this PR.

**Comment by nithinp7** [comment]
From offline discussion, we have decided _not_ to provide backward compatibility with core redirects. The reasoning is that the old behavior was outright broken, so any implementation depending on the old behavior would silently break if we don't do an explicitly breaking change.

**Comment by nithinp7** [comment]
@kring Regarding the ESU <--> Unreal matrix, I think it should just be a plain 3x3 rotation matrix now right? So it shouldn't have any notion of centimeters / meters? 

Otherwise I definitely agree with the ideas you mentioned of explicitly defining local-horizontal coordinate systems to convert between. Although I think there might be a lot of complexity we'll inherit trying to represent arbitrary euler angle conventions in Cesium Native. If Cesium Native can be constrained to _only_ be matrix-based, then we only really have to consider possible left-handed to right-handed CRS switches + scale differences - which is easy. Arbitrary euler angle conventions will get quite tedious to implement - each euler angle convention yields unique matrix <--> euler angles and quaternion <--> euler angle conversions. And of course finding rotations between two CRS with different conventions / handedness is probably undefined.

So anyways... I think it is still convenient to be able to say, here is another local ESU coordinate system with the exact same conventions / handedness as the Unreal world. And we can freely transform anything between this CRS and the Unreal world, without any undefined behavior. If we tried to abstract some of this in Cesium Native, I worry we might enable incorrect / undefined API usage like "convert euler angles from ENU to Unreal" - i.e., the types of things hopefully fixed in this PR.

The formula then, to minimize the pain when implementing new Cesium Native integrations might be:
1) Provide engine <--> Ecef position / direction conversion functions and provide a way to get the actual transformation matrix.
2) Define a local ESU or ENU system (choose based on engine's handedness), this CRS will implicitly have all the other conventions of the engine, including scale and rotation conventions.
3) Provide a way to get the transformation matrix and rotation matrix between this local (georeferenced?) CRS and the engine.
4) Provide a way to convert positions, directions, rotators, euler angles, quaternions, etc. between the local CRS and the engine CRS.
5) _Crucially_, do not provide any rotation conversion functions between the engine CRS and anything else (including ECEF, local tile CRS, or any other ENU / ESU with different conventions). Everything else should be handled with matrices - even 3x3 matrices between such systems should not be _called_ rotation matrices since they might change handedness / scale.

So out of that list 1) could be implemented in Cesium Native, and isn't much work at all. But 2-4 seem to be strictly tied to the particular choices of the game engine, so it makes more sense to me to just implement those conversion functions there. Even converting from engine types to glm types seems error-prone to me when we are talking about euler angles. Hopefully that wasn't too verbose - like you said most of this stuff is out of the scope of this PR anyways, but what do you think?

**Comment by nithinp7** [comment]
@kring Regarding this PR itself, I think it should be good to go. I cleared some of my doubts about whether certain conversions were affected by handedness / conventions. Notably, quaternion <--> matrix conversions do not have a notion of handedness - so we can do them in glm or Unreal equivalently. I also explicitly added a note in the quaternion / matrix --> rotator conversion functions that we assume the input uses Unreal conventions.

**Comment by kring** [comment]
Looks good! I just pushed a small change, to move some comments inside some methods into the doc comments. I'm going to merge it, but please take a quick glance @nithinp7 and tell me if anything looks suspect.

**Pull request merged**
