### PR TITLE
Add developer setup instructions

### LINKED ISSUE #152: Document the need for a release build of cesium-native in a Shipping build of Cesium for Unreal
Hello,

I can run the cesium-unreal-demo in the editor, and I can package the project and then run the exe, works well.

But when I try to add the plugin to my existing project the plugin itself works in the editor, but I cannot package the project anymore, I get an error, see below.

BTW, I added the cesium plugin by checking out the GitHub repo to the Plugin folder of my existing project. Then I followed the make-steps for the plugin (same as in the cesium-unreal-demo, re-created the VS solution files, compiled Cesium when UE started and the plugin works fine in the existing project - only the packaging doesn't work).

The output log:

```
LogUObjectHash: Compacting FUObjectHashTables data took   0.52ms
LogMainFrame: Selected target: CESIUM_TEST
LogLauncherProfile: Unable to use promoted target - ../../../../../../Users/andreas.lepel/Desktop/CESIUM_TEST/Binaries/Win64/CESIUM_TEST-Win64-Shipping.target does not exist.
UATHelper: Packaging (Windows (64-bit)): Running AutomationTool...
UATHelper: Packaging (Windows (64-bit)): Parsing command line: -ScriptsForProject=C:/Users/andreas.lepel/Desktop/CESIUM_TEST/CESIUM_TEST.uproject BuildCookRun -nocompileeditor -installed -nop4 -project=C:/Users/andreas.lepel/Desktop/CESIUM_TEST/CESIUM_TEST.uproject -cook -stage -archive -archivedirectory=C:/Users/andreas.lepel/Desktop/CESIUM_Quickstart -pack
age -ue4exe="C:\Program Files\Epic Games\UE_4.26\Engine\Binaries\Win64\UE4Editor-Cmd.exe" -ddc=InstalledDerivedDataBackendGraph -pak -prereqs -nodebuginfo -targetplatform=Win64 -build -target=CESIUM_TEST -clientconfig=Shipping -utf8output
UATHelper: Packaging (Windows (64-bit)): Setting up ProjectParams for C:\Users\andreas.lepel\Desktop\CESIUM_TEST\CESIUM_TEST.uproject
UATHelper: Packaging (Windows (64-bit)): ********** BUILD COMMAND STARTED **********
UATHelper: Packaging (Windows (64-bit)): Running: C:\Program Files\Epic Games\UE_4.26\Engine\Binaries\DotNET\UnrealBuildTool.exe CESIUM_TEST Win64 Shipping -Project=C:\Users\andreas.lepel\Desktop\CESIUM_TEST\CESIUM_TEST.uproject  C:\Users\andreas.lepel\Desktop\CESIUM_TEST\CESIUM_TEST.uproject -NoUBTMakefiles  -remoteini="C:\Users\andreas.lepel\Desktop\CESIUM
_TEST" -skipdeploy -Manifest=C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Intermediate\Build\Manifest.xml -NoHotReload -log="C:\Users\andreas.lepel\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.26\UBT-CESIUM_TEST-Win64-Shipping.txt"
UATHelper: Packaging (Windows (64-bit)):   WARNING: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/Cesium3DTiles/RelWithDebInfo/Cesium3DTiles.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and
 dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
UATHelper: Packaging (Windows (64-bit)):   WARNING: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/CesiumAsync/RelWithDebInfo/CesiumAsync.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and dep
endency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
UATHelper: Packaging (Windows (64-bit)):   WARNING: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/CesiumGeospatial/RelWithDebInfo/CesiumGeospatial.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is sl
ow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
UATHelper: Packaging (Windows (64-bit)):   WARNING: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/CesiumGeometry/RelWithDebInfo/CesiumGeometry.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow a
nd dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
UATHelper: Packaging (Windows (64-bit)):   WARNING: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/CesiumGltf/RelWithDebInfo/CesiumGltf.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and depen
dency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
UATHelper: Packaging (Windows (64-bit)):   WARNING: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/CesiumGltfReader/RelWithDebInfo/CesiumGltfReader.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is sl
ow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
UATHelper: Packaging (Windows (64-bit)):   WARNING: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/CesiumUtility/RelWithDebInfo/CesiumUtility.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and
 dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
UATHelper: Packaging (Windows (64-bit)):   WARNING: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/extern/uriparser/RelWithDebInfo/uriparser.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and 
dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
UATHelper: Packaging (Windows (64-bit)):   WARNING: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/extern/draco/RelWithDebInfo/draco.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and dependen
cy checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
UATHelper: Packaging (Windows (64-bit)):   WARNING: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/extern/asyncplusplus/RelWithDebInfo/async++.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow an
d dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
UATHelper: Packaging (Windows (64-bit)):   WARNING: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/extern/sqlite3/RelWithDebInfo/sqlite3.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and depe
ndency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
UATHelper: Packaging (Windows (64-bit)):   WARNING: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/extern/tinyxml2/RelWithDebInfo/tinyxml2.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and de
pendency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
UATHelper: Packaging (Windows (64-bit)):   WARNING: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/extern/spdlog/RelWithDebInfo/spdlog.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and depend
ency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
UATHelper: Packaging (Windows (64-bit)):   WARNING: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/extern/modp_b64/RelWithDebInfo/modp_b64.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and de
pendency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
PackagingResults: Warning: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/Cesium3DTiles/RelWithDebInfo/Cesium3DTiles.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and dependency checking will
 not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
PackagingResults: Warning: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/CesiumAsync/RelWithDebInfo/CesiumAsync.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not
 work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
PackagingResults: Warning: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/CesiumGeospatial/RelWithDebInfo/CesiumGeospatial.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and dependency checkin
g will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
PackagingResults: Warning: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/CesiumGeometry/RelWithDebInfo/CesiumGeometry.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and dependency checking wi
ll not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
PackagingResults: Warning: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/CesiumGltf/RelWithDebInfo/CesiumGltf.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not w
ork for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
PackagingResults: Warning: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/CesiumGltfReader/RelWithDebInfo/CesiumGltfReader.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and dependency checkin
g will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
PackagingResults: Warning: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/CesiumUtility/RelWithDebInfo/CesiumUtility.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and dependency checking will
 not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
PackagingResults: Warning: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/extern/uriparser/RelWithDebInfo/uriparser.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and dependency checking will 
not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
PackagingResults: Warning: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/extern/draco/RelWithDebInfo/draco.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work
 for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
PackagingResults: Warning: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/extern/asyncplusplus/RelWithDebInfo/async++.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and dependency checking wil
l not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
PackagingResults: Warning: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/extern/sqlite3/RelWithDebInfo/sqlite3.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not 
work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
PackagingResults: Warning: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/extern/tinyxml2/RelWithDebInfo/tinyxml2.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and dependency checking will no
t work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
PackagingResults: Warning: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/extern/spdlog/RelWithDebInfo/spdlog.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not wo
rk for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
PackagingResults: Warning: Library 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\../../extern/build/cesium-native/extern/modp_b64/RelWithDebInfo/modp_b64.lib' was not resolvable to a file when used in Module 'Cesium', assuming it is a filename and will search library paths for it. This is slow and dependency checking will no
t work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
UATHelper: Packaging (Windows (64-bit)):   Parsing headers for CESIUM_TEST
UATHelper: Packaging (Windows (64-bit)):     Running UnrealHeaderTool "C:\Users\andreas.lepel\Desktop\CESIUM_TEST\CESIUM_TEST.uproject" "C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Intermediate\Build\Win64\CESIUM_TEST\Shipping\CESIUM_TEST.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="C:\User
s\andreas.lepel\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.26\UHT-CESIUM_TEST-Win64-Shipping.txt" -installed
UATHelper: Packaging (Windows (64-bit)):   Reflection code generated for CESIUM_TEST in 4,7628083 seconds
UATHelper: Packaging (Windows (64-bit)):   Writing manifest to C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Intermediate\Build\Manifest.xml
UATHelper: Packaging (Windows (64-bit)):   Building CESIUM_TEST...
UATHelper: Packaging (Windows (64-bit)):   Using Visual Studio 2019 14.28.29337 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29333) and Windows 10.0.18362.0 SDK (C:\Program Files (x86)\Windows Kits\10).
UATHelper: Packaging (Windows (64-bit)):   Building 5 actions with 20 processes...
UATHelper: Packaging (Windows (64-bit)):     [1/5] PCH.Cesium.cpp
UATHelper: Packaging (Windows (64-bit)):     [2/5] Module.Cesium.gen.cpp
UATHelper: Packaging (Windows (64-bit)):     [3/5] Module.Cesium.cpp
UATHelper: Packaging (Windows (64-bit)):     [4/5] CESIUM_TEST-Win64-Shipping.exe
UATHelper: Packaging (Windows (64-bit)):     LINK : fatal error LNK1181: cannot open input file 'C:\Users\andreas.lepel\Desktop\CESIUM_TEST\Plugins\cesium-unreal\Source\Cesium\..\..\extern\build\cesium-native\Cesium3DTiles\RelWithDebInfo\Cesium3DTiles.lib'
UATHelper: Packaging (Windows (64-bit)): Took 43,6668933s to run UnrealBuildTool.exe, ExitCode=6
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool failed. See log for more details. (C:\Users\andreas.lepel\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.26\UBT-CESIUM_TEST-Win64-Shipping.txt)
UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
PackagingResults: Error: Unknown Error
```

### PR DESCRIPTION
**Pull request by javagl**
<sup>This was originally posted as a comment in https://github.com/CesiumGS/cesium-unreal/issues/296 , but now mored here.</sup>

This may fix https://github.com/CesiumGS/cesium-unreal/issues/296 and (when it's fleshed out and extended accordingly), also https://github.com/CesiumGS/cesium-unreal/issues/164 

---

I'm aware that "the real feedback" may come when somebody tried to set up the whole thing, based on this description, *from scratch*. Also, it's currently obviously Windows/VisualStudio-centric, but that's the main development platform for now.

NOTES: 

- The "Generate Visual Studio project files" step only works only after a

      git checkout add-source-folder

  in `C:\Dev\cesium-unreal-samples`

- There currently is no sensible way to to trigger breakpoints in `cesium-native`. Rumours say that it's possible by copy-and-pasting paths from one VS instance to another, but not in a way that would do the term "IDE" (as in "*Integrated* Development Environment") any justice. It *should* be possible to essentially "merge" multiple VS solutions (i.e. open them at the same time), but during my first test, this caused VS to behave erratically. Maybe there is a solution for that that I haven't found yet.

Fixes #152

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @javagl!

* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by xuelongmu** [comment]
One strange thing that I've noticed, having set up the project on multiple computers now, is that when I copy paste all three of the following commands at once into PowerShell to build `cesium-native` after cloning the repo with submodules, UE4 will error on trying to build `cesium-unreal`. 

```
cmake -B build -S .
cmake --build build --config Release --target install
cmake --build build --config Debug --target install 
```

However if I enter all three commands separately, in the above order, waiting for each command to finish before manually pasting in the next one, it will work. Once it reaches the error state, I have had to go back and completely delete the cesium-native folder and re-download that submodule in order to get it to successfully compile.

I will go back later and do some testing to figure out what the error was, and edit this comment.

**Comment by javagl** [comment]
The task to add the steps so that "Generate Visual Studio Project files" works is still on my plate. I'll have to sort out the workflows here (mainly: Understand the workflow where this is *not* necessary...). 

(TODO:  Typo, search `proejct`)

**Comment by kring** [comment]
> The task to add the steps so that "Generate Visual Studio Project files" works is still on my plate.

I'm happy to tackle that while I'm here in here trying the instructions and tweaking some other things.

**Comment by kring** [comment]
@javagl I've added some instructions for converting a Blueprints project to C++, and some other improvements as well. I confirmed that stepping into cesium-native code with the debugger is working ok for me in this setup. Mind giving it a try?

**Comment by javagl** [comment]
I'll have allocate some time to try out the process, starting from a completely clean state, and see at which point something went wrong regarding the possibility to debug-step into `cesium-native`. But even if it works, with copy+pasting paths, I'd also *really* like to try and find a way to combine the projects in Visual Studio, so that they are properly linked and browseable (I mean, I want to CTRL+Click on a class name and just jump there (like with the so-called "hyperlinks", back in the 1990's...)).

---

I *hoped* that we could avoid the duplication that is involved in splitting Linux+Windows, and get away with a single description, and some footnote like <sub>(On linux, use `/` instead of `\`)</sub>. One could also boldly say: "Just use `cmake-gui` - it works on every OS". But ... maybe the current solution is the "nicest" in that regard. 

---

The additional section about "Converting the project" ... is some overhead. We already considered to add some `cesium-unreal-template` project instead. And recently we also considered a dedicated GitHub project for "Developer Tests". **Iff** we decide to create something like that, we'd have

- `cesium-unreal-samples`, which is packaged and published (and targeted at artists and end-users)
- `cesium-unreal-development`, which is *only* for developers, and could contain the `Source` folder and assets for feature- and regression tests

Sure, it's "easy to convert a Blueprints project to a C++ project", but I'd prefer to **not** have to go through this process. Every manual step is a nuisance, and life should be simpler. As a middle-ground, I considered the option to add the files, and just call the folder `Sources_FOR_DEVELOPERS`, so that the "instructions" could just be "Rename that folder to `Sources` and you're done". But having sepearate `samples`<->`development` projects would be cleaner, IMHO.

**Comment by kring** [comment]
> Sure, it's "easy to convert a Blueprints project to a C++ project", but I'd prefer to not have to go through this process.

IMO, maintaining a separate project is a lot more overhead.

> I'd also really like to try and find a way to combine the projects in Visual Studio

I played around with this a bit, but wasn't able to find a good way. Probably the closest I got was by setting Unreal Engine to generate a Visual Studio Code project (I didn't know this was possible until yesterday!). VS Code makes it easy to add multiple independent directories/solutions to a workspace. But it was still clunky, worse IMO than having the two solutions in separate windows.

**Comment by javagl** [comment]
> IMO, maintaining a separate project is a lot more overhead.

With the option to derail into a deeply philosophical discussion here: I often try *to make the life for other people easier*. If everybody did that, ... the "net-difficulty" for everybody would be far lower. 

But leaving the Weltschmerz aside, more pragmatically: 

Won't we need some `c-u-test` or `c-u-development` repo anyhow, to collect test cases that are *not* part of the polished+packaged+published samples? I mean, we don't want some `TilesetThatCausesThatLongStandingBugOfWhichWeDontKnowHowToFixIt` in the samples, but something like this should IMHO definitely be in one place, readily set up to test+tackle it...

**Comment by kring** [comment]
Maintaining multiple projects imposes difficulties on the whole team. Especially given the near-impossibility of diffing/merging Blueprints. Maybe it makes things easier for external contributors. Maybe.

If we eventually have a separate project for other reasons, e.g. a test suite, that's a different matter, of course, and I have no complaint there. But it shouldn't duplicate what's in the cesium-unreal-samples, because then we're back to needing to keep them in sync. 

But a project like that won't eliminate the need to be able to develop/debug the plugin inside cesium-unreal-samples or other Blueprints-only projects. So the instructions are still useful.

If the process seems too hard, we could make it a big easier by providing a zip file (just unzip this to your project directory) or a git repo (just clone it into your Source directory). Or a node script in cesium-unreal that creates the files for you automatically (`npm run convert-project-to-cpp` or something). FWIW, once you've converted a project once, you can copy the Source directory somewhere.... and then if you need to do it again later you just copy it into the new project. It's a little painful, sure, but I still believe it's less painful than all the alternatives.

**Comment by javagl** [comment]
Of course, the issue of possible duplications (and how to quickly test the `samples` after code changes) has to be sorted out. More generally: There should not be so much overlap between the repos. On a second thought: The `test` repo might as well be (or have to be) `private`, because it's not unlikely that some of the test models can not be made public. Regardless of the final solution there, the current instructions say what has to be done *now*, and possible changes will depend on whether or how such a `test` repo will be created.

**Comment by javagl** [comment]
I gave it a stab, and tried to merge *this* PR and https://github.com/CesiumGS/cesium-unreal/pull/471 into https://github.com/CesiumGS/cesium-unreal/pull/481

**Pull request merged**
