### PR TITLE
Update third-party.json license

### PR DESCRIPTION
**Pull request by baothientran**
I'm still unsure about MikkTSpace license. They don't seem to have license file on their repo

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @baothientran!

* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium-unreal/blob/third-party/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by shehzan10** [comment]
@baothientran Looks like MikkTSpace uses a custom open source license with full text here: https://github.com/mmikk/MikkTSpace/blob/master/mikktspace.h.

A comparable is NVIDIA Omniverse - They simply list the license as "mikktspace License" - https://docs.omniverse.nvidia.com/con_connect/common/licenses.html#mikktspace-license

This is similar to what Unreal Engine also does - https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/ThirdParty/Licenses/MikkTSpace_License.txt

So in our case, we should point to the header file and call the license "mikktspace license".

**Comment by shehzan10** [comment]
@baothientran Can you also please sort if by alphabetical order (so some of the new licenses would go in the middle of others)?

**Comment by shehzan10** [comment]
Thanks @baothientran. Looks good to me. I'm merging this without CI since its just a text file change.

**Pull request merged**
