### PR TITLE
add 5 methods for get vertex position

### PR DESCRIPTION
**Pull request by ycn2022**
need to access vertex position, request add 5 methods.

https://community.cesium.com/t/how-to-get-triangle-vertex-position-from-ucesiumgltfprimitivecomponent/22394

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ycn2022!

* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by ycn2022** [comment]
missed some codes

**Comment by ycn2022** [comment]
fixed and reopen

**Comment by kring** [comment]
@ycn2022 can you tell us more about what problem you're solving here? If you just need access to the mesh data, you can get that from Unreal via the `UCesiumGltfPrimitiveComponent`, which derives from `UStaticMeshComponent`.

**Comment by ycn2022** [comment]
@kring  some model cannot be hit by UKismetSystemLibrary::LineTraceSingle, I have report here:
https://github.com/CesiumGS/cesium-unreal/issues/1038
I need to query the hit by FIntrRay3Triangle3d, so I want to access vertex position from UStaticMesh of UStaticMeshComponent.
I success in Develop Editor Configuration, but report a error when package in Shipping, this question is here:
https://community.cesium.com/t/how-to-get-triangle-vertex-position-from-ucesiumgltfprimitivecomponent/22394
So I want to access these data via GetFirstVertexIDFromFaceID meshod.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @ycn2022! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Pull request closed without merging**
