### PR TITLE
Android Target Platform Support

### PR DESCRIPTION
**Pull request by shehzan10**
This draft PR is a work in progress. The current state is that Cesium Native and the Cesium for Unreal plugin compile for Android, but cannot be packaged as an APK with Cesium for Unreal Samples, or even for Android debugging mode.

See full notes in #190.

Before packaging Cesium for Unreal Samples, In File -> Package Project -> Project Settings, please set the following (or edit the `Config/DefaultEngine.ini` file)

```
+[/Script/AndroidRuntimeSettings.AndroidRuntimeSettings]
+MinSDKVersion=26
+bBuildForArmV7=False
+bBuildForArm64=True
+bSupportsVulkan=True
+bBuildForES31=False
+InstallLocation=Auto
+PackageName=com.Cesium.CesiumForUnrealSamples
+TargetSDKVersion=26
+ApplicationDisplayName=Cesium_For_Unreal
```

#### Preprocessor Definitions

Based on the suggestion in https://github.com/CesiumGS/cesium-unreal/issues/190#issuecomment-843468951, I added `-D__ANDROID__ -DANDROID_LOGGING` to both the `unreal-android-toolchain` file and to the `CesiumRuntime.Build.cs` files (using appropriate syntax). This however didn't help so I haven't pushed it up.

Patch file: [preprocessor.diff.txt](https://github.com/CesiumGS/cesium-unreal/files/6510992/preprocessor.diff.txt)

`__ANDROID__` is supposed to be a built-in definition in the compiler, but I haven't verified that it was coming in for cross compilation.

When I tried to run ` C:/Users/smohammed/AppData/Local/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe  -E -dM - < /dev/null`, it did not print the Android preprocessor definitions.

#### MikkTSpace and `genTangSpaceDefault`

This is a function we use from the Unreal Engine source modules. It includes a library for aarch64, but for some reason the build system is not picking the library up, resulting in a undefined reference error.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @shehzan10!

* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by shehzan10** [comment]
Steps to cross compile for Android are here https://github.com/CesiumGS/cesium-unreal/blob/android-platform/Documentation/development-guide.md#android.

**Comment by shehzan10** [comment]
@kring Not sure if its because of some file being removed in the manual edits, but plugin build tool errors out with that Android is not a supported platform. https://travis-ci.com/github/CesiumGS/cesium-unreal/jobs/506474910 (Only says this in the Branch build. The PR build seems to be erroring out much earlier for some reason)

**Comment by kring** [comment]
I didn't end up doing any manual edits, but I did de-select the "Linux" support and the "Engine Source Code" option. I can't think of why either of those should bre required, but I'll check it out today. This page makes it sound like UE is super picky about the versions of Android things: https://answers.unrealengine.com/questions/991480/view.html

**Comment by kring** [comment]
Hmm I made a trivial change to print the build log so we could get more details about what's going wrong... and now the Branch build is failing in the same way the PR one was before. 🤔

**Comment by kring** [comment]
The Android plugin package is succeeding on Travis now. I'm looking into the linker errors at game package time.

**Comment by kring** [comment]
The game package succeeds now. It crashes on startup on my ancient Nexus 6P, but hey, progress!

**Comment by kring** [comment]
Looks like it might be related to our old friend SQLite. From `adb logcat`:

```
05-21 17:24:47.864 32434 32434 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
05-21 17:24:47.871 32434 32434 F DEBUG   : Abort message: 'terminating with uncaught exception of type std::runtime_error: disk I/O error'
```

**Comment by kring** [comment]
I commented-out the SQLite cache, and now it runs!

Screenshot_20210521-173759

There were a bunch of errors compiling materials during packaging, so unsurprisingly the materials are all missing. But CWT is clearly showing up, and it's perfectly smooth flying around even on this 6 year old phone.

This is an OpenGL ES 3.1 build. I also tried Vulkan, but this phone doesn't seem to support it. But even the Vulkan build reports lots of errors with our materials:

```
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Warning: Failed to compile Material /CesiumForUnreal/Materials/M_CesiumOverlayComplexWater.M_CesiumOverlayComplexWater for platform SF_VULKAN_ES31_ANDROID_NOUB, Default Material will be used in game.
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2025): error: array index must be integer type
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2025): error: 'return' with wrong type , in function 'CustomExpression0' returning half2
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2059): error: array index must be integer type
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2059): error: 'return' with wrong type , in function 'CustomExpression4' returning half2
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2066): error: array index must be integer type
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2066): error: 'return' with wrong type , in function 'CustomExpression5' returning half2
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2073): error: array index must be integer type
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2073): error: 'return' with wrong type , in function 'CustomExpression6' returning half2
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2080): error: array index must be integer type
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2080): error: 'return' with wrong type , in function 'CustomExpression7' returning half2
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2087): error: array index must be integer type
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2087): error: 'return' with wrong type , in function 'CustomExpression8' returning half2
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2120): error: array index must be integer type
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2120): error: 'return' with wrong type , in function 'CustomExpression12' returning half2
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2127): error: array index must be integer type
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2127): error: 'return' with wrong type , in function 'CustomExpression13' returning half2
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2160): error: array index must be integer type
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2160): error: 'return' with wrong type , in function 'CustomExpression17' returning half2
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2167): error: array index must be integer type
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2167): error: 'return' with wrong type , in function 'CustomExpression18' returning half2
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(3118): warning: implicit truncation from 'half3' to 'half'
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(3121): warning: implicit truncation from 'half3' to 'half'
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(3122): warning: implicit truncation from 'half3' to 'half'
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(3123): warning: implicit truncation from 'half3' to 'half'
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(3127): warning: implicit truncation from 'half3' to 'half'
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2025): error: 'return' with wrong type , in function 'CustomExpression0' returning vec2
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2059): error: 'return' with wrong type , in function 'CustomExpression4' returning vec2
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2066): error: 'return' with wrong type , in function 'CustomExpression5' returning vec2
PackagingResults: Warning: Failed to compile Material /CesiumForUnreal/Materials/M_CesiumOverlayComplexWater.M_CesiumOverlayComplexWater for platform SF_VULKAN_ES31_ANDROID_NOUB, Default Material will be used in game.
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2073): error: 'return' with wrong type , in function 'CustomExpression6' returning vec2
PackagingResults: Error: array index must be integer type
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression0' returning half2
PackagingResults: Error: array index must be integer type
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression4' returning half2
PackagingResults: Error: array index must be integer type
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression5' returning half2
PackagingResults: Error: array index must be integer type
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2080): error: 'return' with wrong type , in function 'CustomExpression7' returning vec2
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression6' returning half2
PackagingResults: Error: array index must be integer type
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression7' returning half2
PackagingResults: Error: array index must be integer type
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression8' returning half2
PackagingResults: Error: array index must be integer type
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression12' returning half2
PackagingResults: Error: array index must be integer type
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2087): error: 'return' with wrong type , in function 'CustomExpression8' returning vec2
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression13' returning half2
PackagingResults: Error: array index must be integer type
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression17' returning half2
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2120): error: 'return' with wrong type , in function 'CustomExpression12' returning vec2
PackagingResults: Error: array index must be integer type
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2127): error: 'return' with wrong type , in function 'CustomExpression13' returning vec2
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2160): error: 'return' with wrong type , in function 'CustomExpression17' returning vec2
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression18' returning half2
PackagingResults: Warning: implicit truncation from 'half3' to 'half'
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(2167): error: 'return' with wrong type , in function 'CustomExpression18' returning vec2
PackagingResults: Warning: implicit truncation from 'half3' to 'half'
PackagingResults: Warning: implicit truncation from 'half3' to 'half'
PackagingResults: Warning: implicit truncation from 'half3' to 'half'
PackagingResults: Warning: implicit truncation from 'half3' to 'half'
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(3118): warning: implicit truncation from 'vec3' to 'float'
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression0' returning vec2
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression4' returning vec2
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression5' returning vec2
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression6' returning vec2
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression7' returning vec2
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression8' returning vec2
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression12' returning vec2
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(3121): warning: implicit truncation from 'vec3' to 'float'
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression13' returning vec2
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression17' returning vec2
PackagingResults: Error: 'return' with wrong type , in function 'CustomExpression18' returning vec2
PackagingResults: Warning: implicit truncation from 'vec3' to 'float'
PackagingResults: Warning: implicit truncation from 'vec3' to 'float'
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(3122): warning: implicit truncation from 'vec3' to 'float'
PackagingResults: Warning: implicit truncation from 'vec3' to 'float'
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(3123): warning: implicit truncation from 'vec3' to 'float'
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   LogShaderCompilers: Display:   /Engine/Generated/Material.ush(3127): warning: implicit truncation from 'vec3' to 'float'
PackagingResults: Warning: implicit truncation from 'vec3' to 'float'
PackagingResults: Warning: implicit truncation from 'vec3' to 'float'
```

**Comment by kring** [comment]
To (temporarily) disable the SQLite request cache:

```
diff --git a/Source/CesiumRuntime/Private/Cesium3DTileset.cpp b/Source/CesiumRuntime/Private/Cesium3DTileset.cpp
index 61332f9..c06a98f 100644
--- a/Source/CesiumRuntime/Private/Cesium3DTileset.cpp
+++ b/Source/CesiumRuntime/Private/Cesium3DTileset.cpp
@@ -639,13 +639,15 @@ static std::string getCacheDatabaseName() {
 }

 void ACesium3DTileset::LoadTileset() {
+  // static std::shared_ptr<CesiumAsync::IAssetAccessor> pAssetAccessor =
+  //    std::make_shared<CesiumAsync::CachingAssetAccessor>(
+  //        spdlog::default_logger(),
+  //        std::make_shared<UnrealAssetAccessor>(),
+  //        std::make_shared<CesiumAsync::SqliteCache>(
+  //            spdlog::default_logger(),
+  //            getCacheDatabaseName()));
   static std::shared_ptr<CesiumAsync::IAssetAccessor> pAssetAccessor =
-      std::make_shared<CesiumAsync::CachingAssetAccessor>(
-          spdlog::default_logger(),
-          std::make_shared<UnrealAssetAccessor>(),
-          std::make_shared<CesiumAsync::SqliteCache>(
-              spdlog::default_logger(),
-              getCacheDatabaseName()));
+      std::make_shared<UnrealAssetAccessor>();

   Cesium3DTiles::Tileset* pTileset = this->_pTileset;
```

**Comment by shehzan10** [comment]
@getinthedamnbox @CesiumBen @ggetz It might be worth testing the current state of support for Android on the VR headsets. Here are the steps to follow:

1. Follow https://docs.unrealengine.com/en-US/SharingAndReleasing/Mobile/Android/Setup/AndroidStudio/index.html to get Android Studio set up for Unreal Engine use.
2. Download the latest build of this PR from travis ("combined" tag)
3. Extract this to `C:\Program Files\Epic Games\UE_4.26\Engine\Plugins\Marketplace\CesiumForUnreal`.
4. Clone Cesium for Unreal Samples.
5. Follow the project setting changes in https://github.com/CesiumGS/cesium-unreal/pull/443#issue-647951727. (We'll open a PR for Unreal Samples soon with these changes)

This should now allow you to build for Android. You can then use that to test on the Quest, but you probably know more about that workflow than I do.

**Comment by getinthedamnbox** [comment]
@shehzan10 Awesome, looking forward to trying it. Can you please tell me how I can download a build from Travis? Don't see that option.

**Comment by shehzan10** [comment]
@getinthedamnbox click "Show all checks" to see the builds, and then click the details link next to the combined build.

image

image

**Comment by kring** [comment]
I decided to try to figure out why the SQLite cache is causing a crash at startup. Here's a summary of my (lack of) progress.

The story is, the sqlite3_open completes succesfully. The .sqlite file is created with zero length (which is the same behavior I see on Windows). But then when we attempt to create the cache table, sqlite3_exec fails with `SQLITE_IOERR`. After enabling more detailed IO errors (`sqlite3_extended_result_codes`), it reports `SQLITE_IOERR_SEEK`. So we can create a file just fine, but can't seek within it? Seriously?

I disabled WAL mode, and made sure to delete the .sqlite file on my device before launching the app, but it didn't make any difference.

So at this point I decided I needed a debugger. Instructions for setting that up are [here](https://docs.unrealengine.com/en-US/SharingAndReleasing/Mobile/Android/AndroidDebugging/index.html). Do you think debugging cesium-native in Cesium for Unreal on Windows is a hassle? Wait til you see this! Anyway, it kind of works, if you Clean builds just right and recompile things manually and generally muck around every time you want to change the code. My process (surely I'm missing something, it can't really be this hard, can it?!) goes roughly like this:

* Package the game for Android once to get all the data in the right place I guess.
* Build the C++ code for Android from the command line:

```powershell
."C:\Program Files\Epic Games\UE_4.26\Engine\Binaries\DotNET\UnrealBuildTool.exe" dev Android Development -Project=C:\Dev\cesium-unreal-samples\CesiumForUnrealSamples.uproject -Clean -NoHotReload C:\Dev\cesium-unreal-samples\CesiumForUnrealSamples.uproject -NoUBTMakefiles  -remoteini="C:\Dev\cesium-unreal-samples" -skipdeploy -nobuilduht -log="C:\Users\kring\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.26\UBT-dev-Android-Development.txt"; ."C:\Program Files\Epic Games\UE_4.26\Engine\Binaries\DotNET\UnrealBuildTool.exe" dev Android Development -Project=C:\Dev\cesium-unreal-samples\CesiumForUnrealSamples.uproject C:\Dev\cesium-unreal-samples\CesiumForUnrealSamples.uproject -NoUBTMakefiles  -remoteini="C:\Dev\cesium-unreal-samples" -skipdeploy -Manifest=C:\Dev\cesium-unreal-samples\Intermediate\Build\Manifest.xml -NoHotReload -log="C:\Users\kring\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.26\UBT-dev-Android-Development_2.txt"
```

* In Android Studio, go to Build -> Clean Project, followed by Run -> Debug 'app-app`.
* If that fails (mysterious errors from the build step or the Debug step), Clean again, then build again, then clean again, then debug again. I suspect sacrificing an Android-themed stuffed animal or two couldn't hurt, but I don't have any and my kids probably wouldn't let me try it anyway. 🤷 

Oh and by the way, every step of the above takes approximately forever, so have fun with that.

With that it quickly (build time aside) became clear that the game is using the UE version of SQLite on Android. Which _might_ be the problem, but it's hard to tell because the UE version of SQLite doesn't have any debug symbols, so we can't step into the sqlite code and see what's going wrong. I tried disabling UE's SQLite plugin, but that only yields this rather infurating error at startup:

image

(in case it's not clear, that message is infurating because I _did_ disable the plugin, and that's what caused this error. 🙄)

Not sure what the next step is other than to sleep and hope for a brilliant flash of insight (most likely from someone else reading this) by the morning.

**Comment by baothientran** [comment]
> Which might be the problem, but it's hard to tell because the UE version of SQLite doesn't have any debug symbols, so we can't step into the sqlite code and see what's going wrong

I had this problem before and the only solution I had at that time is to compile the UE4 manually as Debug configure (not DebugGame) and use the built engine to open the project. After that, I was able to step into sqlite source code, which should be sqlite3.inl file for Unreal version

**Comment by getinthedamnbox** [comment]
I followed the instructions in [this comment](https://github.com/CesiumGS/cesium-unreal/pull/443#issuecomment-846087443) to try to build and deploy to the Quest, and I got these build errors:

```
LogPlayLevel:   Building 4 actions with 12 processes...
LogPlayLevel:     [1/4] SharedPCH.Engine.ShadowErrors.h [armv7]
LogPlayLevel:     [2/4] CesiumForUnrealSamples.cpp [armv7]
LogPlayLevel:     [3/4] CesiumForUnrealSamples-armv7.so
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libasync++.a(scheduler.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libCesium3DTiles.a(BingMapsRasterOverlay.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libCesium3DTiles.a(BoundingVolume.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libCesium3DTiles.a(CreditSystem.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libCesium3DTiles.a(IonRasterOverlay.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libCesium3DTiles.a(RasterOverlayCollection.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libCesium3DTiles.a(TileMapServiceRasterOverlay.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libCesium3DTiles.a(Tileset.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libCesium3DTiles.a(ViewState.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libCesium3DTiles.a(registerAllTileContentTypes.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libCesiumAsync.a(CachingAssetAccessor.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libCesiumAsync.a(HttpHeaders.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libCesiumAsync.a(SqliteCache.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libCesiumGeometry.a(AxisTransforms.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libCesiumGeospatial.a(Ellipsoid.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libCesiumGeospatial.a(GlobeRectangle.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libCesiumGeospatial.a(Transforms.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libCesiumGltf.a(Accessor.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libMikkTSpace.a(mikktspace.c.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: C:/Program Files/Epic Games/UE_4.26/Engine/Plugins/Marketplace/CesiumForUnreal/Source/ThirdParty/lib/Android-xaarch64\libspdlog.a(spdlog.cpp.o) is incompatible with armelf_linux_eabi
LogPlayLevel: Error:     ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
LogPlayLevel: Error:     clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Here's the full log: [UBT-CesiumForUnrealSamples-Android-Development.txt](https://github.com/CesiumGS/cesium-unreal/files/6534961/UBT-CesiumForUnrealSamples-Android-Development.txt)

I'll go over the steps again to see if I missed anything, but let me know if anyone has tips.

**Comment by kring** [comment]
I've seen those errors. In my case it was caused by forgetting to switch the project to target 64-bit ARM instead of 32-bit. In the Editor, go to Edit -> Project Settings -> Platforms -> Android -> Build. Then uncheck "Support armv7" and check "Support arm64":

image

Shehzan suggested switching from OpenGL ES3.1 to Vulkan, too, but that'll depend on your device.

**Comment by kring** [comment]
Actually you'll need to check arm64 _first_ before you try to uncheck armv7, or else the editor won't let you. 😆

**Comment by getinthedamnbox** [comment]
Thanks @kring, that was it. I had a typo in my `DefaultEngine.ini` file, which made it keep switching back to armv7. In [this comment](https://github.com/CesiumGS/cesium-unreal/pull/443#issue-647951727),

```
+[/Script/AndroidRuntimeSettings.AndroidRuntimeSettings]
```

should be

```
[/Script/AndroidRuntimeSettings.AndroidRuntimeSettings]
```

The application builds and runs now, but it crashes on start. I tried both Vulkan and OpenGL. Here's the log for OpenGL: [CesiumForUnrealSamples (Quest 2, OpenGL).log](https://github.com/CesiumGS/cesium-unreal/files/6541092/CesiumForUnrealSamples.Quest.2.OpenGL.log)

**Comment by kring** [comment]
@getinthedamnbox the crash on start can be fixed by hacking out the request cache:

```
diff --git a/Source/CesiumRuntime/Private/Cesium3DTileset.cpp b/Source/CesiumRuntime/Private/Cesium3DTileset.cpp
index 61332f9..c06a98f 100644
--- a/Source/CesiumRuntime/Private/Cesium3DTileset.cpp
+++ b/Source/CesiumRuntime/Private/Cesium3DTileset.cpp
@@ -639,13 +639,15 @@ static std::string getCacheDatabaseName() {
 }

 void ACesium3DTileset::LoadTileset() {
+  // static std::shared_ptr<CesiumAsync::IAssetAccessor> pAssetAccessor =
+  //    std::make_shared<CesiumAsync::CachingAssetAccessor>(
+  //        spdlog::default_logger(),
+  //        std::make_shared<UnrealAssetAccessor>(),
+  //        std::make_shared<CesiumAsync::SqliteCache>(
+  //            spdlog::default_logger(),
+  //            getCacheDatabaseName()));
   static std::shared_ptr<CesiumAsync::IAssetAccessor> pAssetAccessor =
-      std::make_shared<CesiumAsync::CachingAssetAccessor>(
-          spdlog::default_logger(),
-          std::make_shared<UnrealAssetAccessor>(),
-          std::make_shared<CesiumAsync::SqliteCache>(
-              spdlog::default_logger(),
-              getCacheDatabaseName()));
+      std::make_shared<UnrealAssetAccessor>();

   Cesium3DTiles::Tileset* pTileset = this->_pTileset;
```

I'm working on a proper fix.

**Comment by kring** [comment]
After the above commits:
* Debug builds no longer assert/crash with a ColorVertexBuffer-related error. Also we can use Settings -> Preview Rendering Level -> Android ES 3.1 on desktop and it doesn't crash anymore.
* The SQLite cache works now. No need to be disable it to avoid a crash on startup.
* Fixes #245, all the SQLite problems, I think (but not well tested yet).

**Comment by kring** [comment]
Materials are working now, too. The problem was that the custom `CesiumSelectTexCoords` function was trying to index an array with a float, which I guess is automatically converted to an int on desktop platforms. On Android we have to convert the float to an int explicitly.

My old Nexus 6P again:
Screenshot_20210527-173226

**Comment by shehzan10** [comment]
@kring Looks great and I was able to run it on my Samsung S21 as well. It complained about old Android build and stuff, but it worked.

Do you know why the SunSky is not loading? I ran the Denver photogrammetry level from Samples, and it was very dark because its not doing GI and indirect lighting.

**Comment by kring** [comment]
> Do you know why the SunSky is not loading?

I suspect the SkyAtmosphere just isn't supported on Android, but that's only a guess.

**Comment by shehzan10** [comment]
> I suspect the SkyAtmosphere just isn't supported on Android, but that's only a guess.

@kring So I asked this to UDN during the day, and they said it should be supported. https://udn.unrealengine.com/s/question/0D54z00006xC6vHCAS/compiling-cesium-for-unreal-code-plugin-for-android (click "Show more Answers" towards the bottom).

I'll try creating a small test project with SunSky and see if that works.

**Comment by shehzan10** [comment]
@kring I added a new level to Cesium Unreal Samples from the template "Time of Day" level, and that runs fine on Android. It uses separate actors for Sky Light, Sky Atmosphere, Sky dome mesh.

However, hiding those actors and adding just the SunSky doesn't seem to work for some reason. The component properties as far as I checked match the individual actors from the template.

**Comment by shehzan10** [comment]
> However, hiding those actors and adding just the SunSky doesn't seem to work for some reason. The component properties as far as I checked match the individual actors from the template.

SunSky + SkyDomeMesh from the template works well and the lighting is good.

**Comment by kring** [comment]
I'm going to merge this once CI is happy. I don't know if we're quite ready to call Android support official, but this is a big step in that direction and shouldn't cause problems for other platforms. It also fixes #245. We'll write separate issues for any remaining work.

**Comment by AaronCederberg** [comment]
@getinthedamnbox — were you able to sort out the problem with the app crashing on the oculus quest?

**Pull request merged**
