### PR TITLE
Support compressed textures

### PR DESCRIPTION
**Pull request by nithinp7**
Builds on: https://github.com/CesiumGS/cesium-native/pull/402

Main changes:
- Reports the supported gpu pixel compression formats that KTXv2 (either ETC1S and UASTC) textures can be transcoded to.
- Integrates compression formats received from Cesium Native into Unreal's texture system.
- Integrates pre-computed mip maps received from Cesium Native. This is especially useful for compressed textures that would be hard to generate mipmaps for.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @nithinp7!

* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium-unreal/blob/ktx2-nithin/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by lilleyse** [comment]
@nithinp7 do you have more details about this PR and possibly any screenshots?

**Comment by nithinp7** [comment]
@lilleyse This is in a very early stage, so I'm not even entirely sure which compression formats Unreal will be able to support. But this corresponds to KTX support in cesium-native. Currently it is pretty much just the hardcoded dxt1 transcoding that you implemented for the hackathon.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @nithinp7! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by nithinp7** [comment]
@kring This PR as well as the [corresponding Cesium Native PR](https://github.com/CesiumGS/cesium-native/pull/402) are ready for a first pass review. You can skim through the code or try it out. I still have some more in-depth testing I plan on doing tomorrow to make sure it is working as expected in all cases.

**Comment by kring** [comment]
@nithinp7 this all looks good to me. A little cleanup and a CHANGES.md update needed probably, but the architecture looks solid.

**Comment by kring** [comment]
This works well and the code looks solid. Thanks @nithinp7!

**Pull request merged**
