### PR TITLE
support of  WMTS (see CesiumGS/cesium-native#714) on UE side

### PR DESCRIPTION
**Pull request by EzioHelios**
Unreal side of CesiumGS/cesium-native#714 to see if WMTS imagery works

Sample screenshots:
Snipaste_2023-10-10_14-27-17
Snipaste_2023-10-10_14-30-49

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @EzioHelios! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @EzioHelios! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by EzioHelios** [comment]
Making new commits and hoping it could catch up with the latest changes.

**Comment by kring** [comment]
Thanks @EzioHelios!

**Pull request merged**
