### PR TITLE
Add screenspacecontroller support for cesium unreal

### PR DESCRIPTION
**Pull request by jiangheng90**
this pull request is relate to #1449

### CODE REVIEW

**Comment by kring** [comment]
Merging this into a branch in the main repo, as discussed. Thanks @jiangheng90!

**Comment by mercy089** [comment]
note getting
 Content/Input/IA_Pan.uasset
 Content/Input/IA_Rotate.uasset
 Content/Input/IA_Zoom.uasset
 Content/Input/IMC_Default.uasset
 these file in repo
 can you add these file repo

**Comment by kring** [comment]
I can see those files in the repo @mercy089:
https://github.com/CesiumGS/cesium-unreal/tree/screen-space-controller/Content/Input

**Comment by mercy089** [comment]
Thank you sir

**Comment by mercy089** [comment]
First of all, thank you for the amazing work on this integration. I'm currently working on a project in Unreal Engine 5 using Cesium for Unreal along with the Google Maps API. I’ve successfully set up Cesium ion and enabled 3D Tiles for rendering the globe.

My goal is to replicate basic Google Earth-style mouse controls, such as:

Freely rotating and tilting the globe in 3D

Zooming in/out smoothly with the mouse scroll

Clicking or double-clicking to zoom into a location

Drag to pan across the globe

I attempted to implement these interactions using C++ in Unreal Engine, but I'm encountering multiple issues and errors during implementation. I would highly appreciate a step-by-step guide or best practices to achieve the following:

Setting up smooth 3D globe navigation with mouse input

Implementing camera movement and rotation properly using Cesium's API or Unreal's controller

Handling zoom & tilt functionalities without breaking the globe rendering

If there are any recommended examples, documentation, or sample projects related to this use case, kindly point me in that direction.

Thanks in advance for your time and support!

**Comment by jiangheng90** [comment]
@mercy089 sorry, I really wanna to help. but for now I'm not working on unreal, even on cpp. since this feature is finish over an year. I don't have a env to run this.
second, all the implement is comes from matrix calculation. and it is design for starter use. since I open source the implement, I think for pro user is easy to modify. but for starter may be should start with the  linear algebra.

**Comment by kring** [comment]
Thanks again for your contribution @jiangheng90, and for chiming in!

**Comment by mercy089** [comment]
Thank you for finally implementing this feature! I've successfully completed the integration in my project. Big thanks to @jiangheng90  and @kring

**Comment by mercy089** [comment]
Is it possible to add a player using a ScreenSpaceController and also enable player movement?

**Comment by jiangheng90** [comment]
> Is it possible to add a player using a ScreenSpaceController and also enable player movement?

you can use two different pawn to switch control, but use player movement on ScreenSpaceController you probably will meet unexpected problem. ScreenSpaceController is based on a geospatial coord system, and ScreenSpaceController has a different way to handle collision with unreal mesh. so if u want to use player movement, just make another pawn and switch to it.

**Comment by CoulterMDP** [comment]
> Thank you for finally implementing this feature! I've successfully completed the integration in my project. Big thanks to @jiangheng90 and @kring

Hi Mercy. Could you give a brief overview on how you implemented this merge, especially in newer Cesium for Unreal versions? Have you made your own Cesium for UE version with a custom pawn and movement system? 
- I'm just not sure how to take these changes and make them work in my own project.

**Comment by mercy089** [comment]
> > Thank you for finally implementing this feature! I've successfully completed the integration in my project. Big thanks to @jiangheng90 and @kring
> 
> Hi Mercy. Could you give a brief overview on how you implemented this merge, especially in newer Cesium for Unreal versions? Have you made your own Cesium for UE version with a custom pawn and movement system?
> 
> * I'm just not sure how to take these changes and make them work in my own project.

Hey! I’ve modified the Cesium code to work with Unreal Engine version 5.3.2 according to my setup. I’ll share the file with you via Google Drive. Can you please share your email ID so I can give you access? 😊

**Comment by kring** [comment]
@mercy089 may I suggest you create a fork of the cesium-unreal repo on GitHub and push your code to that? You could even consider opening ap ull request into this screen-space-controller branch.

**Comment by CsloudX** [comment]
Hi, friends. how to use this ScreenSpaceController? i'm look for a tutorial.

**Comment by jo-chemla** [comment]
demo video [here](https://www.youtube.com/watch?v=6DO3AzR0BGs)

**Pull request merged**
