### PR TITLE
fixed issue#1025 wherein GlobeAwareDefaultPawn causes stall when flyToGranularityDegrees is 0

### LINKED ISSUE #1025: `GlobeAwareDefaultPawn` causes stall when `flyToGranularityDegrees` is 0
This was discovered in https://github.com/CesiumGS/cesium-unity/pull/154. The code for computing the flight path of `GlobeAwareDefaultPawn` does not account for the case when `flyToGranularityDegrees` is 0. This results in a divide by zero error and an infinite `for` loop that stalls the editor.

https://github.com/CesiumGS/cesium-unreal/blob/8e65171bca1dbae5e57e60c9efa75f87f60ab0a9/Source/CesiumRuntime/Private/GlobeAwareDefaultPawn.cpp#L110-L112

For Cesium for Unity, we [logged an error](https://github.com/CesiumGS/cesium-unity/blob/main/Runtime/CesiumFlyToController.cs#L357-L363) whenever `FlyToLocation` was called with `flyToGranularityDegrees` set to 0. Then, the function would return early. This should be done similarly in Cesium for Unreal. It may also help to [log a warning](https://github.com/CesiumGS/cesium-unity/blob/96c8dbdab9b18944d308301edb7b31c6bc769848/Runtime/CesiumFlyToController.cs#L102-L108) if the user sets the value to zero.

### PR DESCRIPTION
**Pull request by shourya5**
- [x] fixes #1025 
- [x] added early return when flyToGranularityDegrees is 0
- [x] added an error log for when flyToGranularityDegrees is 0

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @shourya5! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
    * Maintainers, [here's how to check](https://github.com/CesiumGS/cesium/blob/master/Documentation/Contributors/CLAs/README.md) for a submitted CLA.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by shourya5** [comment]
I have signed the Contributor License Agreement (CLA)

**Comment by kring** [comment]
Thanks for the PR @shourya5. Did you test out the change, though? I see a typo that should prevent it from even compiling.

**Comment by j9liu** [comment]
I'm going to close this PR due to inactivity, but feel free to reopen @shourya5 if you make changes!

**Pull request closed without merging**
