### PR TITLE
Update `CesiumRuntime.Build.cs` for Cesium Native changes

### PR DESCRIPTION
**Pull request by j9liu**
- Updates for KTX library changes: `ktx_read` -> `ktx`
- Adds new `CesiumQuantizedMeshTerrain` namespace

### CODE REVIEW

**Comment by csciguy8** [comment]
Look like good changes to update cesium-native.

Seeing this weird CI error across all iOS versions...
`CMake Error at cesium-native/CMakeLists.txt:210 (install):
  install TARGETS given no FRAMEWORK DESTINATION for static library FRAMEWORK
  target "ktx".`

Not obvious why this is occurring. Looking into it... (unless you beat me to it)

**Comment by j9liu** [comment]
Earlier in the CI logs I see this error as well:

> CMake Warning at cesium-native/extern/KTX-Software/cmake/version.cmake:151 (message):
  Error retrieving version from GIT tag.  Falling back to 0.0.0-noversion
Call Stack (most recent call first):
  cesium-native/extern/KTX-Software/CMakeLists.txt:13 (include)

**Comment by csciguy8** [comment]
I think I have a fix for the iOS cmake errors.

Needed a cesium-native change, so I committed that update.

This PR now depends on [cesium-native PR 869](https://github.com/CesiumGS/cesium-native/pull/869)

**Review by csciguy8 — APPROVED** [review]
Thanks @j9liu !

Lots of changes to sync up on here.

**Comment by j9liu** [comment]
@csciguy8 I was making some changes to sync with the new cesium-native changes. I'm going to cancel your CI build and push them to main directly.

**Comment by csciguy8** [comment]
Whoops! Go for it.

**Pull request merged**
