### PR TITLE
Add support for ellipsoid tileset loader

### PR DESCRIPTION
**Pull request by jqntn**
Hi,

Pretty much the same as https://github.com/CesiumGS/cesium-unity/pull/467, but for Unreal :)

### CODE REVIEW

**Comment by kring** [comment]
Looks great, thanks @jqntn!

**Comment by crydotsnake** [comment]
Hello everyone! @jqntn @kring 

Could maybe anyone tell me how this works and how i can try this out in a newly created unreal engine project? Thanks in advance!

**Comment by kring** [comment]
@crydotsnake in Cesium for Unreal v2.11.0+, you just need to add a blank Cesium3DTileset to your level using the Cesium panel, then change the "Tileset Source" to "From WGS84 Ellipsoid".

If you have followup questions, please post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10).

**Comment by crydotsnake** [comment]
> @crydotsnake in Cesium for Unreal v2.11.0+, you just need to add a blank Cesium3DTileset to your level using the Cesium panel, then change the "Tileset Source" to "From WGS84 Ellipsoid".
> 
> If you have followup questions, please post to the [community forum](https://community.cesium.com/c/cesium-for-unreal/10).

Hi @kring! I think its just called: "Source". And as option i only had: "From Ellipsoid".


## Before
image

## After
image

**Pull request merged**
