### PR TITLE
Update Windows Setup Instructions for VS

### PR DESCRIPTION
**Pull request by miatang13**
- Updates the set up guide for Windows system to include .NET, which is a dependency for Unreal Engine.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @miatang13! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by kring** [comment]
Thanks @miatang13! I've never had to explicitly install .NET for UE, though, so I'm curious why it was necessary in your case. When you installed Visual Studio, did you select the "Game development with C++" workload? What problem did you run into before you installed it?

**Comment by shehzan10** [comment]
@kring @miatang13 I did not install `Game Development with C++`. If you think that is the right way to go, then maybe we should add it here https://github.com/CesiumGS/cesium-unreal/blob/ue5-main/Documentation/developer-setup-windows.md#prerequisities.

**Comment by kring** [comment]
It's in Unreal's docs for setting up Visual Studio:
https://docs.unrealengine.com/5.0/en-US/setting-up-visual-studio-development-environment-for-cplusplus-projects-in-unreal-engine/

But we should mention it here, too, because people won't necessarily see or follow those instructions.

**Comment by shehzan10** [comment]
> But we should mention it here, too, because people won't necessarily see or follow those instructions.

That sounds reasonable to me.

**Comment by shehzan10** [comment]
@kring I updated the setup instructions. Please merge if they look good to you.

**Comment by kring** [comment]
Thanks @shehzan10!

**Comment by kring** [comment]
And @miatang13!

**Pull request merged**
