### PR TITLE
Disable support for water mask on Mac

### PR DESCRIPTION
**Pull request by nithinp7**
I don't have a Mac to test this on, but this should prevent a horrible crash on Mac that seems to be caused by using the water material. In the future once we figure out what's causing it, we may be able to come up with a fix that allows water mask to be supported on Mac.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @nithinp7!

* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by xuelongmu** [comment]
I just pushed a way to check for Mac platform by storing the Platform Name in a UPROPERTY and doing a check in the `EditCondition` to see if PlatformName = TEXT("Mac"). If true, the property check box should be (hopefully) disabled.

The other way to do it (which might be more typical UE4 programming style) is to wrap the entire `EnableWaterMask` in an ifdef, so that the property does not show up at all on Mac. Any usages of `EnableWaterMask` property would then also have to be wrapped.

**Comment by shehzan10** [comment]
Please make sure you open an issue to add the support back.

**Comment by kring** [comment]
I don't have a Mac to test this on either, but it looks ok. I'm going to merge it to work toward a final release candidated we can test (including on Mac for real).

**Pull request merged**
