### PR TITLE
Add an option for enabling translucency on a tileset

### PR DESCRIPTION
**Pull request by installgentoo**
Add optional translucent material
and assign it to translucent elements on gltf load

See https://community.cesium.com/t/missing-polygons-within-tileset/18980/13

By default translucent elements get assigned the same default masked material, as, judging by comments elsewhere in the code,  translucency may cause crashes on mac, plus we don't want to enable blending and increase number of shaders unless users specifically desire to handle translucency.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @installgentoo! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
    * Maintainers, [here's how to check](https://github.com/CesiumGS/cesium/blob/master/Documentation/Contributors/CLAs/README.md) for a submitted CLA.

Reviewers, don't forget to make sure that:

- [ ] [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples) works.

**Comment by shehzan10** [comment]
@installgentoo Thanks. I can confirm that the CLA was signed.

**Comment by kring** [comment]
Thanks for the pull request @installgentoo, and sorry for the delay in reviewing it. This looks really good, nice work! I made a few small changes, and now I'll merge this:

* Added a translucent material out of the box. Hopefully one new material isn't too painful from a "number of materials" point of view, and it seems worthwhile in this case.
* Updated some doc comments.
* Fixed a typo.
* Enabled translucent support on Mac, too. As far as I know the problem on Mac was only with water, not with translucency in general. @joseph-kaile would you mind trying it out on your Mac to be sure? You can use https://sandcastle.cesium.com/SampleData/Cesium3DTiles/Batched/BatchedTranslucent/tileset.json as a test.
* Merged in ue4-main, and retargeted this to merge into ue4-main.

**Comment by joseph-kaile** [comment]
Yes, the translucency works on Mac.

**Pull request merged**
